version: "2.4"

services:
  theisland:
    image: nhalase/arkmanager:0.1.41
    environment:
      SERVER_MAP: TheIsland
      CLUSTER_ID: ${CLUSTER_ID}
      SESSION_NAME: ark-theisland.nws.monster
      SERVER_PASSWORD: ${THE_ISLAND_SERVER_PASSWORD}
      SPECTATOR_PASSWORD: ${THE_ISLAND_SPECTATOR_PASSWORD}
      SERVER_ADMIN_PASSWORD: ${THE_ISLAND_SERVER_ADMIN_PASSWORD}
      DISCORD_WEBHOOK_URL: ${THE_ISLAND_DISCORD_WEBHOOK_URL}
      PORT: 7778
      QUERY_PORT: 27015
      RCON_ENABLED: 'true'
      RCON_PORT: 32330
      NO_PORT_DECREMENT: 'false'
      GCLOUD_SERVICE_ACCOUNT_KEY: ${GCLOUD_SERVICE_ACCOUNT_KEY}
      GCLOUD_BACKUP_BUCKET_NAME: ${THE_ISLAND_GCLOUD_BACKUP_BUCKET_NAME}
      CLOUD_SDK_ARCHIVE: ${CLOUD_SDK_ARCHIVE}
      ARK_LOG_FLAG: 'false'
      ARK_SERVER_GAME_LOG_FLAG: 'false'
      ADMIN_LOGGING: 'true'
      AUTO_SAVE_PERIOD_MINUTES: 20.0
      SHOW_MAP_PLAYER_LOCATION: 'true'
      GLOBAL_VOICE_CHAT: 'true'
      OVERRIDE_STRUCTURE_PLATFORM_PREVENTION: 'true'
      PREVENT_OFFLINE_PVP: 'true'
      ALLOW_ANYONE_BABY_IMPRINT_CUDDLE: 'true'
      DISABLE_IMPRINT_DINO_BUFF: 'true'
      SERVER_CROSSHAIR: 'true'
      ENABLE_PVP_GAMMA: 'true'
      DISABLE_PVE_GAMMA: 'false'
      OVERRIDE_OFFICIAL_DIFFICULTY: 5.0
      DIFFICULTY_OFFSET: 1.0
      ALLOW_FLYER_CARRY_PVE: 'true'
      PREVENT_SPAWN_ANIMATIONS: 'true'
      NON_PERMANENT_DISEASES: 'true'
      ALLOW_MULTIPLE_ATTACHED_C4: 'true'
      ALLOW_HIT_MARKERS: 'true'
      DESTROY_UNCONNECTED_WATER_PIPES: 'true'
      DISABLE_STRUCTURE_DECAY_PVE: 'true'
      ALLOW_CRATE_SPAWNS_ON_TOP_OF_STRUCTURE: 'true'
      ALWAYS_NOTIFY_PLAYER_LEFT: 'true'
      ALWAYS_NOTIFY_PLAYER_JOINED: 'true'
      ALLOW_CAVE_BUILDING_PVE: 'true'
      ALLOW_CAVE_BUILDING_PVP: 'true'
      FORCE_FLYER_EXPLOSIVES: 'true'
      DINO_CHARACTER_FOOD_DRAIN_MULTIPLIER: 5.00000
      HARVEST_HEALTH_MULTIPLIER: 2.00000
      HARVEST_AMOUNT_MULTIPLIER: 3.00000
      XP_MULTIPLIER: 5.00000
      MATING_INTERVAL_MULTIPLIER: 0.10000
      MATING_SPEED_MULTIPLIER: 3.00000
      EGG_HATCH_SPEED_MULTIPLIER: 10.00000
      BABY_MATURE_SPEED_MULTIPLIER: 10.00000
      MAX_GATE_FRAME_ON_SADDLES: 2.00000
      DAY_TIME_SPEED_SCALE: 0.60000
      NIGHT_TIME_SPEED_SCALE: 1.80000
      SUPPLY_CRATE_LOOT_QUALITY_MULTIPLIER: 5.00000
      FISHING_LOOT_QUALITY_MULTIPLIER: 5.00000
      NO_BATTLEYE: 'true'
      NO_ANTISPEED_HACK: 'true'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    cpus: '4.0'
    cpuset: '0-15'
    mem_limit: 12G
    mem_reservation: 6G
    volumes:
      - ark_server_theisland:/ark
      - ark_cluster:/cluster
    ports:
      - "32330:32330/tcp"
      - "7777:7777/udp"
      - "7778:7778/udp"
      - "27015:27015/udp"

  lostisland:
    image: nhalase/arkmanager:0.1.41
    environment:
      SERVER_MAP: LostIsland
      CLUSTER_ID: ${CLUSTER_ID}
      SESSION_NAME: ark-lostisland.nws.monster
      SERVER_PASSWORD: ${LOST_ISLAND_SERVER_PASSWORD}
      SPECTATOR_PASSWORD: ${LOST_ISLAND_SPECTATOR_PASSWORD}
      SERVER_ADMIN_PASSWORD: ${LOST_ISLAND_SERVER_ADMIN_PASSWORD}
      DISCORD_WEBHOOK_URL: ${LOST_ISLAND_DISCORD_WEBHOOK_URL}
      PORT: 7780
      QUERY_PORT: 27016
      RCON_ENABLED: 'true'
      RCON_PORT: 32331
      NO_PORT_DECREMENT: 'false'
      GCLOUD_SERVICE_ACCOUNT_KEY: ${GCLOUD_SERVICE_ACCOUNT_KEY}
      GCLOUD_BACKUP_BUCKET_NAME: ${LOST_ISLAND_GCLOUD_BACKUP_BUCKET_NAME}
      CLOUD_SDK_ARCHIVE: ${CLOUD_SDK_ARCHIVE}
      ARK_LOG_FLAG: 'false'
      ARK_SERVER_GAME_LOG_FLAG: 'false'
      ADMIN_LOGGING: 'true'
      AUTO_SAVE_PERIOD_MINUTES: 20.0
      SHOW_MAP_PLAYER_LOCATION: 'true'
      GLOBAL_VOICE_CHAT: 'true'
      OVERRIDE_STRUCTURE_PLATFORM_PREVENTION: 'true'
      PREVENT_OFFLINE_PVP: 'true'
      ALLOW_ANYONE_BABY_IMPRINT_CUDDLE: 'true'
      DISABLE_IMPRINT_DINO_BUFF: 'true'
      SERVER_CROSSHAIR: 'true'
      ENABLE_PVP_GAMMA: 'true'
      DISABLE_PVE_GAMMA: 'false'
      OVERRIDE_OFFICIAL_DIFFICULTY: 5.0
      DIFFICULTY_OFFSET: 1.0
      ALLOW_FLYER_CARRY_PVE: 'true'
      PREVENT_SPAWN_ANIMATIONS: 'true'
      NON_PERMANENT_DISEASES: 'true'
      ALLOW_MULTIPLE_ATTACHED_C4: 'true'
      ALLOW_HIT_MARKERS: 'true'
      DESTROY_UNCONNECTED_WATER_PIPES: 'true'
      DISABLE_STRUCTURE_DECAY_PVE: 'true'
      ALLOW_CRATE_SPAWNS_ON_TOP_OF_STRUCTURE: 'true'
      ALWAYS_NOTIFY_PLAYER_LEFT: 'true'
      ALWAYS_NOTIFY_PLAYER_JOINED: 'true'
      ALLOW_CAVE_BUILDING_PVE: 'true'
      ALLOW_CAVE_BUILDING_PVP: 'true'
      FORCE_FLYER_EXPLOSIVES: 'true'
      DINO_CHARACTER_FOOD_DRAIN_MULTIPLIER: 5.00000
      HARVEST_HEALTH_MULTIPLIER: 2.00000
      HARVEST_AMOUNT_MULTIPLIER: 3.00000
      XP_MULTIPLIER: 5.00000
      MATING_INTERVAL_MULTIPLIER: 0.10000
      MATING_SPEED_MULTIPLIER: 3.00000
      EGG_HATCH_SPEED_MULTIPLIER: 10.00000
      BABY_MATURE_SPEED_MULTIPLIER: 10.00000
      MAX_GATE_FRAME_ON_SADDLES: 2.00000
      DAY_TIME_SPEED_SCALE: 0.60000
      NIGHT_TIME_SPEED_SCALE: 1.80000
      SUPPLY_CRATE_LOOT_QUALITY_MULTIPLIER: 5.00000
      FISHING_LOOT_QUALITY_MULTIPLIER: 5.00000
      NO_BATTLEYE: 'true'
      NO_ANTISPEED_HACK: 'true'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    cpus: '4.0'
    cpuset: '16-31'
    mem_limit: 12G
    mem_reservation: 6G
    volumes:
      - ark_server_lostisland:/ark
      - ark_cluster:/cluster
    ports:
      - "32331:32331/tcp"
      - "7779:7779/udp"
      - "7780:7780/udp"
      - "27016:27016/udp"

  valguero:
    image: nhalase/arkmanager:0.1.41
    environment:
      SERVER_MAP: Valguero_P
      CLUSTER_ID: ${CLUSTER_ID}
      SESSION_NAME: ark-valguero.nws.monster
      SERVER_PASSWORD: ${VALGUERO_SERVER_PASSWORD}
      SPECTATOR_PASSWORD: ${VALGUERO_SPECTATOR_PASSWORD}
      SERVER_ADMIN_PASSWORD: ${VALGUERO_SERVER_ADMIN_PASSWORD}
      DISCORD_WEBHOOK_URL: ${VALGUERO_DISCORD_WEBHOOK_URL}
      PORT: 7782
      QUERY_PORT: 27017
      RCON_ENABLED: 'true'
      RCON_PORT: 32332
      NO_PORT_DECREMENT: 'false'
      GCLOUD_SERVICE_ACCOUNT_KEY: ${GCLOUD_SERVICE_ACCOUNT_KEY}
      GCLOUD_BACKUP_BUCKET_NAME: ${VALGUERO_GCLOUD_BACKUP_BUCKET_NAME}
      CLOUD_SDK_ARCHIVE: ${CLOUD_SDK_ARCHIVE}
      ARK_LOG_FLAG: 'false'
      ARK_SERVER_GAME_LOG_FLAG: 'false'
      ADMIN_LOGGING: 'true'
      AUTO_SAVE_PERIOD_MINUTES: 20.0
      SHOW_MAP_PLAYER_LOCATION: 'true'
      GLOBAL_VOICE_CHAT: 'true'
      OVERRIDE_STRUCTURE_PLATFORM_PREVENTION: 'true'
      PREVENT_OFFLINE_PVP: 'true'
      ALLOW_ANYONE_BABY_IMPRINT_CUDDLE: 'true'
      DISABLE_IMPRINT_DINO_BUFF: 'true'
      SERVER_CROSSHAIR: 'true'
      ENABLE_PVP_GAMMA: 'true'
      DISABLE_PVE_GAMMA: 'false'
      OVERRIDE_OFFICIAL_DIFFICULTY: 5.0
      DIFFICULTY_OFFSET: 1.0
      ALLOW_FLYER_CARRY_PVE: 'true'
      PREVENT_SPAWN_ANIMATIONS: 'true'
      NON_PERMANENT_DISEASES: 'true'
      ALLOW_MULTIPLE_ATTACHED_C4: 'true'
      ALLOW_HIT_MARKERS: 'true'
      DESTROY_UNCONNECTED_WATER_PIPES: 'true'
      DISABLE_STRUCTURE_DECAY_PVE: 'true'
      ALLOW_CRATE_SPAWNS_ON_TOP_OF_STRUCTURE: 'true'
      ALWAYS_NOTIFY_PLAYER_LEFT: 'true'
      ALWAYS_NOTIFY_PLAYER_JOINED: 'true'
      ALLOW_CAVE_BUILDING_PVE: 'true'
      ALLOW_CAVE_BUILDING_PVP: 'true'
      FORCE_FLYER_EXPLOSIVES: 'true'
      DINO_CHARACTER_FOOD_DRAIN_MULTIPLIER: 5.00000
      HARVEST_HEALTH_MULTIPLIER: 2.00000
      HARVEST_AMOUNT_MULTIPLIER: 3.00000
      XP_MULTIPLIER: 5.00000
      MATING_INTERVAL_MULTIPLIER: 0.10000
      MATING_SPEED_MULTIPLIER: 3.00000
      EGG_HATCH_SPEED_MULTIPLIER: 10.00000
      BABY_MATURE_SPEED_MULTIPLIER: 10.00000
      MAX_GATE_FRAME_ON_SADDLES: 2.00000
      DAY_TIME_SPEED_SCALE: 0.60000
      NIGHT_TIME_SPEED_SCALE: 1.80000
      SUPPLY_CRATE_LOOT_QUALITY_MULTIPLIER: 5.00000
      FISHING_LOOT_QUALITY_MULTIPLIER: 5.00000
      NO_BATTLEYE: 'true'
      NO_ANTISPEED_HACK: 'true'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    cpus: '4.0'
    cpuset: '0-15'
    mem_limit: 12G
    mem_reservation: 6G
    volumes:
      - ark_server_valguero:/ark
      - ark_cluster:/cluster
    ports:
      - "32332:32332/tcp"
      - "7781:7781/udp"
      - "7782:7782/udp"
      - "27017:27017/udp"

  ragnarok:
    image: nhalase/arkmanager:0.1.41
    environment:
      SERVER_MAP: Ragnarok
      CLUSTER_ID: ${CLUSTER_ID}
      SESSION_NAME: ark-ragnarok.nws.monster
      SERVER_PASSWORD: ${RAGNAROK_SERVER_PASSWORD}
      SPECTATOR_PASSWORD: ${RAGNAROK_SPECTATOR_PASSWORD}
      SERVER_ADMIN_PASSWORD: ${RAGNAROK_SERVER_ADMIN_PASSWORD}
      DISCORD_WEBHOOK_URL: ${RAGNAROK_DISCORD_WEBHOOK_URL}
      PORT: 7784
      QUERY_PORT: 27018
      RCON_ENABLED: 'true'
      RCON_PORT: 32333
      NO_PORT_DECREMENT: 'false'
      GCLOUD_SERVICE_ACCOUNT_KEY: ${GCLOUD_SERVICE_ACCOUNT_KEY}
      GCLOUD_BACKUP_BUCKET_NAME: ${RAGNAROK_GCLOUD_BACKUP_BUCKET_NAME}
      CLOUD_SDK_ARCHIVE: ${CLOUD_SDK_ARCHIVE}
      ARK_LOG_FLAG: 'false'
      ARK_SERVER_GAME_LOG_FLAG: 'false'
      ADMIN_LOGGING: 'true'
      AUTO_SAVE_PERIOD_MINUTES: 20.0
      SHOW_MAP_PLAYER_LOCATION: 'true'
      GLOBAL_VOICE_CHAT: 'true'
      OVERRIDE_STRUCTURE_PLATFORM_PREVENTION: 'true'
      PREVENT_OFFLINE_PVP: 'true'
      ALLOW_ANYONE_BABY_IMPRINT_CUDDLE: 'true'
      DISABLE_IMPRINT_DINO_BUFF: 'true'
      SERVER_CROSSHAIR: 'true'
      ENABLE_PVP_GAMMA: 'true'
      DISABLE_PVE_GAMMA: 'false'
      OVERRIDE_OFFICIAL_DIFFICULTY: 5.0
      DIFFICULTY_OFFSET: 1.0
      ALLOW_FLYER_CARRY_PVE: 'true'
      PREVENT_SPAWN_ANIMATIONS: 'true'
      NON_PERMANENT_DISEASES: 'true'
      ALLOW_MULTIPLE_ATTACHED_C4: 'true'
      ALLOW_HIT_MARKERS: 'true'
      DESTROY_UNCONNECTED_WATER_PIPES: 'true'
      DISABLE_STRUCTURE_DECAY_PVE: 'true'
      ALLOW_CRATE_SPAWNS_ON_TOP_OF_STRUCTURE: 'true'
      ALWAYS_NOTIFY_PLAYER_LEFT: 'true'
      ALWAYS_NOTIFY_PLAYER_JOINED: 'true'
      ALLOW_CAVE_BUILDING_PVE: 'true'
      ALLOW_CAVE_BUILDING_PVP: 'true'
      FORCE_FLYER_EXPLOSIVES: 'true'
      DINO_CHARACTER_FOOD_DRAIN_MULTIPLIER: 5.00000
      HARVEST_HEALTH_MULTIPLIER: 2.00000
      HARVEST_AMOUNT_MULTIPLIER: 3.00000
      XP_MULTIPLIER: 5.00000
      MATING_INTERVAL_MULTIPLIER: 0.10000
      MATING_SPEED_MULTIPLIER: 3.00000
      EGG_HATCH_SPEED_MULTIPLIER: 10.00000
      BABY_MATURE_SPEED_MULTIPLIER: 10.00000
      MAX_GATE_FRAME_ON_SADDLES: 2.00000
      DAY_TIME_SPEED_SCALE: 0.60000
      NIGHT_TIME_SPEED_SCALE: 1.80000
      SUPPLY_CRATE_LOOT_QUALITY_MULTIPLIER: 5.00000
      FISHING_LOOT_QUALITY_MULTIPLIER: 5.00000
      NO_BATTLEYE: 'true'
      NO_ANTISPEED_HACK: 'true'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    cpus: '4.0'
    cpuset: '16-31'
    mem_limit: 12G
    mem_reservation: 6G
    volumes:
      - ark_server_ragnarok:/ark
      - ark_cluster:/cluster
    ports:
      - "32333:32333/tcp"
      - "7783:7783/udp"
      - "7784:7784/udp"
      - "27018:27018/udp"

volumes:
  ark_server_theisland:
  ark_server_valguero:
  ark_server_ragnarok:
  ark_server_lostisland:
  ark_cluster:
